name: Android CI

on:
  push:
    branches:
      - master  # or 'master', depending on your default branch
  pull_request:
    branches:
      - master # or 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'  # Specify the Java distribution

    - name: Set permissions for gradlew
      run: chmod +x ./gradlew  # Add execute permissions to the gradlew script

    - name: Clean and Build APK
      run: ./gradlew clean assembleRelease --stacktrace


    - name: Build APK
      run: ./gradlew assembleRelease

    - name: ls
      run: ls app/build/outputs

    - name: Upload APK to release
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/app-release.apk
